version: 2.1

orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@4.7

jobs:
  unit-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      # - node/install
      - run: npm install
      - run:
          name: Run Unit tests
          command: npm test
  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Installing deployment dependencies
          command: |
            - docker build -t stephengrider/multi-client ./client
            - docker build -t stephengrider/multi-nginx ./nginx
            - docker build -t stephengrider/multi-server ./server
            - docker build -t stephengrider/multi-worker ./worker
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
            - docker push stephengrider/multi-client
            - docker push stephengrider/multi-nginx
            - docker push stephengrider/multi-server
            - docker push stephengrider/multi-worker

workflows:
  version: 2.1
  build_deploy:
    jobs:
      - unit-test
      - deploy:
          requires:
            - unit-test