version: 2.1

orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@4.7

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Installing deployment dependencies
          command: |
            docker build -t stephengrider/multi-client ./client
            docker build -t stephengrider/multi-nginx ./nginx
            docker build -t stephengrider/multi-server ./server
            docker build -t stephengrider/multi-worker ./worker
            # echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
            docker login -u "$DOCKER_PASSWORD" -p "$DOCKER_ID" docker.io
            docker push stephengrider/multi-client
            docker push stephengrider/multi-nginx
            docker push stephengrider/multi-server
            docker push stephengrider/multi-worker

workflows:
  version: 2.1
  build_deploy:
    jobs:
      - deploy
